apiVersion: apps/v1
kind: Deployment
metadata:
  name: master-service
spec:
  selector:
    matchLabels:
      run: master-service
  replicas: 1
  template:
    metadata:
      labels:
        run: master-service
    spec:
      containers:
      - name: master-service
        image: 889945364708.dkr.ecr.ap-south-1.amazonaws.com/aggrqatest/master-service:1-0-2
        ports:
        - containerPort: 4200
---
apiVersion: v1
kind: Service
metadata:
  name: master-service
  labels:
    run: master-service
spec:
  ports:
  - port: 4200
    protocol: TCP
    targetPort: 4200
  type: ClusterIP
  selector:
    run: master-service
